# Generated by Django 2.0.8 on 2018-09-15 07:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherprofile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('teacher_id', models.CharField(blank=True, default='', max_length=7, null=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='profilepics/')),
                ('mobile_number', models.BigIntegerField(blank=True, default=9999999999)),
                ('department', models.CharField(blank=True, default='', max_length=40)),
                ('last_lecture', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('dob', models.DateField(blank=True, default=datetime.datetime.now)),
                ('address', models.CharField(blank=True, default='', max_length=100)),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('education', models.CharField(blank=True, default='', max_length=50)),
                ('subject', models.ManyToManyField(blank=True, null=True, to='subject.subject')),
            ],
        ),
    ]
