# Generated by Django 2.0.8 on 2018-09-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20180915_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='class_TG',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='last_student_rollno',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='start_student_rollno',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
