# Generated by Django 2.0.8 on 2018-09-18 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20180917_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='is_HOD',
            field=models.BooleanField(default='False'),
        ),
    ]
