# Generated by Django 2.0.8 on 2018-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacherprofile_is_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='RFID',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='is_HOD',
            field=models.BooleanField(default=False),
        ),
    ]
