# Generated by Django 2.0.8 on 2018-10-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('teacher', '0006_remove_teacherprofile_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='subject',
            field=models.ManyToManyField(blank=True, to='subject.subject'),
        ),
    ]
