# Generated by Django 2.0.8 on 2018-09-17 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('subject', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='section',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='Class',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='subject',
            field=models.ManyToManyField(blank=True, to='subject.subject'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_no',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
