# Generated by Django 2.0.8 on 2018-09-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20180917_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
