# Generated by Django 2.0.8 on 2018-09-22 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20180918_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='Class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classes.classes'),
        ),
    ]
