# Generated by Django 2.0.8 on 2018-09-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20180922_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='subject.subject'),
        ),
    ]
