# Generated by Django 2.0.8 on 2018-10-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20180928_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='RFID',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
