# Generated by Django 2.0.8 on 2018-10-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
        ('student', '0007_remove_studentprofile_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='subject.subject'),
        ),
    ]
