# Generated by Django 2.0.8 on 2018-09-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='rollcall_end',
            field=models.CharField(blank=True, default='000999', max_length=6),
        ),
        migrations.AddField(
            model_name='classes',
            name='rollcall_start',
            field=models.CharField(blank=True, default='000000', max_length=6),
        ),
    ]
