# Generated by Django 2.0.8 on 2018-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'PRESENT'), ('A', 'ABSENT')], default='P', max_length=1),
        ),
    ]
